# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIn28NlVkoo9Rwawu44tUnCIkIEfQ50Y
"""

import pandas as pd
teachers=pd.DataFrame({
    "FISH":['Qadamavo Z','Xalilov D','Abdullayeva M','Xontorayev S','Tillaboyev M','Jorayeva G','Qurbonova G','Djalilov M','Raxmatov R','Turdimatov M' ],
    'Fani':["Sun`iy intelekt asoslar","Sun`iy intelekt asoslar",'Malumotlar tuzilmasi va algoritmlar','Malumotlar tuzilmasi va algoritmlar','Elektronika va sxemalar','Elektronika va sxemalar',
            'Kompyutern tashkil etish', 'Kompyutern tashkil etish','KIberxavfsizlik asoslari','KIberxavfsizlik asoslari'],
    "Mashg`ulot turi":['amaliy','maruza','amaliy','maruza','amaliy','maruza','amaliy','maruza','amaliy','maruza'],
    "dars o'tish maxorat":['yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi']
})
print(teachers)